- hosts: db_servers
  remote_user: ubuntu
  vars_files:
  - group_vars/db_servers
  roles:
    - mysql
    
- hosts: web_servers
  remote_user: ubuntu
  vars_files:
  - group_vars/web_servers
  - group_vars/web_prod
  - group_vars/web_uat
  roles:
    - apache
